import _ from './libs/atomic_/core.js';
import $ from './libs/atomic_/shell.js';
import * as b from './backgammon.js';
import {reg} from './libs/cmd.js';

const $state = $.atom(b.init());
const moves = _.pipe(_.deref, b.moves, _.toArray, $.see("moves"));

reg({$state, moves, b});

$.swap($state, b.roll([5, 6]));
$.swap($state, b.move(11, 5));
$.swap($state, b.move(16, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(7, 6));
$.swap($state, b.move(7, 6));
$.swap($state, b.move(12, 6));
$.swap($state, b.move(12, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 1]));
$.swap($state, b.move(11, 6));
$.swap($state, b.move(17, 1));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(7, 6));
$.swap($state, b.move(12, 6));
$.swap($state, b.move(12, 6));
$.swap($state, b.move(12, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([3, 3]));
$.swap($state, b.move(11, 3));
$.swap($state, b.move(11, 3));
$.swap($state, b.move(0, 3));
$.swap($state, b.move(0, 3));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(6, 6));
$.swap($state, b.move(6, 6));
$.swap($state, b.move(23, 6));
$.swap($state, b.move(23, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([1, 2]));
$.swap($state, b.move(3, 1));
$.swap($state, b.move(16, 2));
$.swap($state, b.commit());
$.swap($state, b.roll([5, 5]));
$.swap($state, b.move(5, 5));
$.swap($state, b.move(6, 5));
$.swap($state, b.commit());
$.swap($state, b.roll([1, 2]));
$.swap($state, b.move(22, 1));
$.swap($state, b.move(11, 2));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(17, 6));
$.swap($state, b.move(17, 6));
$.swap($state, b.move(11, 6));
$.swap($state, b.move(11, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([1, 2]));
$.swap($state, b.move(3, 1));
$.swap($state, b.move(13, 2));
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(4, 6));
$.swap($state, b.move(4, 6));
$.swap($state, b.move(10, 6));
$.swap($state, b.move(10, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([1, 2]));
$.swap($state, b.move(5, 1));
$.swap($state, b.move(4, 2));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(14, 6));
$.swap($state, b.move(14, 6));
$.swap($state, b.move(15, 6));
$.swap($state, b.move(16, 6));
$.swap($state, b.commit());
$.swap($state, b.roll([1, 2]));
$.swap($state, b.move(1, 1));
$.swap($state, b.move(2, 2));
$.swap($state, b.commit());
$.swap($state, b.roll([6, 6]));
$.swap($state, b.move(16, 6));
$.swap($state, b.move(16, 6));
$.swap($state, b.move(16, 6));

moves($state);
